// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDua_Uu_7K2sta7riUReF3OFYOdODBGVwM',
    appId: '1:255933498392:web:2588c53c9d3c0489772f6d',
    messagingSenderId: '255933498392',
    projectId: 'rafeeq-f408a',
    authDomain: 'rafeeq-f408a.firebaseapp.com',
    storageBucket: 'rafeeq-f408a.firebasestorage.app',
    measurementId: 'G-306MS4Q475',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFbL03K23r-d-cz-NFm1d7ZSi1f9ejkz8',
    appId: '1:255933498392:ios:463e90cf2dd7c455772f6d',
    messagingSenderId: '255933498392',
    projectId: 'rafeeq-f408a',
    storageBucket: 'rafeeq-f408a.firebasestorage.app',
    iosBundleId: 'com.example.elderlyCompanionFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFbL03K23r-d-cz-NFm1d7ZSi1f9ejkz8',
    appId: '1:255933498392:ios:463e90cf2dd7c455772f6d',
    messagingSenderId: '255933498392',
    projectId: 'rafeeq-f408a',
    storageBucket: 'rafeeq-f408a.firebasestorage.app',
    iosBundleId: 'com.example.elderlyCompanionFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDua_Uu_7K2sta7riUReF3OFYOdODBGVwM',
    appId: '1:255933498392:web:22a21d8222141423772f6d',
    messagingSenderId: '255933498392',
    projectId: 'rafeeq-f408a',
    authDomain: 'rafeeq-f408a.firebaseapp.com',
    storageBucket: 'rafeeq-f408a.firebasestorage.app',
    measurementId: 'G-KT1KE7FKZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrOdVCB4NZwYFVg3lpqqoXEjEm4ma7jdc',
    appId: '1:255933498392:android:724940a419011834772f6d',
    messagingSenderId: '255933498392',
    projectId: 'rafeeq-f408a',
    storageBucket: 'rafeeq-f408a.firebasestorage.app',
  );
}
